name: Minimal Test

on:
  push:
    branches: [ main ]

jobs:
  minimal:
    name: Minimal Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Check if project compiles
      run: cargo check


