name: Step-by-Step Recovery

on:
  push:
    branches: [ main ]

jobs:
  step1_build:
    name: Step 1: Build Only
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Build
      run: cargo build

  step2_tests:
    name: Step 2: Build + Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Build
      run: cargo build
    
    - name: Run tests
      run: cargo test

  step3_format:
    name: Step 3: Build + Tests + Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    
    - name: Build
      run: cargo build
    
    - name: Run tests
      run: cargo test
    
    - name: Check formatting
      run: cargo fmt --all -- --check
